### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by NaraSakamoto** [lauradefreitas2/fleet-management-api#1]
Laura,

Deixo aqui algumas sugestões para você continuar a sua jornada de estudos!

Para continuar se aprimorando como Desenvolvedora Backend Java, sugiro se aprofundar em:

1. Linguagem Java, que você já conhece boa parte, mas busque sempre se aprimorar.. Existem detalhes que sempre deixamos passar e podem ser essenciais. E para isso deixo algumas sugestões de estudo prático de Java para você escolher, além disso, se possível, tire a certificação Java:

 - [ ] [exercism](https://exercism.org/tracks/java)
 - [ ] [Code Academy](https://www.codecademy.com/learn/learn-java)
 - [ ] [Hacker Rank](https://www.hackerrank.com/domains/java)
 - [ ] [Java Caminhos de Certificação](https://education.oracle.com/pt_BR/oracle-certification-path/pFamily_48)
 
2.   Conceitos de Programação Orientada a Objetos. Sugiro alguns cursos gratuitos, escolha um para fazer:

 - [ ] [Fundação Bradesco](https://www.ev.org.br/cursos/introducao-a-programacao-orientada-a-objetos-poo).
 - [ ] [Dev Dojo - Maratona Java](https://youtu.be/VKjFuX91G5Q?feature=shared). Esse curso é bem atual, vale a pena. 
 
3. Se aprofundar na construção de APIs REST usando Spring Boot, inclusive finalizando o projeto Fleet Management. Caso queira fazer outras APIs, vc pode tentar construir a API do Burguer Queen usando Spring Boot e Java! Deixei o link aqui em baixo. Sugiro aqui também alguns cursos gratuitos como:

 - [ ] [Spring Boot 3 | Complete Course 2023](https://www.youtube.com/watch?v=wlYvA2b1BWI).
 - [ ] [Desafio Vagas: API de tarefas com Spring Boot!](https://www.youtube.com/watch?v=IjProDV001o). Esse vídeo a apresentadora mostra um desafio de uma vaga de emprego.
 - [ ] [Dev Dojo - Spring Boot Essentials 2](https://youtube.com/playlist?list=PL62G310vn6nFBIxp6ZwGnm8xMcGE3VA5H&feature=shared)
 - [ ] [Burguer Queen API](https://github.com/Laboratoria/SAP011-burger-queen-api)

4. Inicie seus estudos em Cloud Computing. Como muitas empresas utilizam AWS, recomendo que inicie seus estudos por ela. 
 - [ ] [AWS Educate](https://aws.amazon.com/pt/education/awseducate/?trk=8c29b82a-1d1c-47a7-a99b-21eafe50c48e&sc_channel=el). Neste link você encontrará conteúdos que te ajudarão com os estudos de Cloud Computing. É gratuito e bem prático. 
 - [ ] [AWS Certification](https://aws.amazon.com/pt/certification/?nc2=sb_ce_co). Neste link você poderá buscar por uma certificação. Infelizmente a certificação é paga, mas o estudo é gratuito. Vale a pena dar uma olhada.

Revisando os seus Objetivos de Aprendizagem de cada um dos projetos da Laboratória, deixo aqui algumas sugestões de estudos que podem complementar o seu aprendizado.
 
Sobre HTML Semântico, veja um pouco sobre isso nesses conteúdos abaixo, mas pratique! Tente aplicar em seus próximos HTMLs:
- [ ] [Devmedia HTML Semântico](https://www.devmedia.com.br/html-semantico-conheca-os-elementos-semanticos-da-html5/38065)
- [ ] [Elementos semânticos do HTML5 explicados](https://www.freecodecamp.org/portuguese/news/elementos-semanticos-do-html5-explicados/)

Sobre recursão: 
Sobre Interfaces Java: 

- [ ]  Você pode iniciar seus estudos por esses conteúdos que deixo abaixo:
    - [ ]  [POO em Java - Compreendendo as Interfaces](https://www.dio.me/articles/poo-em-java-compreendendo-as-interfaces)
    - [ ]  [Interfaces em Java explicadas com exemplos](https://www.freecodecamp.org/portuguese/news/interfaces-em-java-explicadas-com-exemplos/)
    - [ ]  [Exercício sobre Interfaces - Exercism](https://exercism.org/tracks/java/concepts/interfaces)
    - [ ]  [Interfaces - Java Documentation](https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html)
    

Parabéns pela sua jornada ao longo do Bootcamp, Laura! Você aproveitou bastante todas as oportunidades de aprendizagem!
Foi só o começo da sua carreira de sucesso na Tecnologia!

Beijos!
